#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#No shareable history
setopt append_history no_inc_append_history no_share_history

#EC2 Stuff
export JAVA_HOME="$(/usr/libexec/java_home)"
export AWS_ACCESS_KEY="AKIAIBUH4L4ULC47DOEQ"
export AWS_SECRET_KEY="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"
export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.7.1.0/libexec"

##Boot2docker stuff
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Volumes/Extra/pinnokio/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

#Aliases
alias sshconfig="vim ~/.ssh/config"
alias zc="vim ~/.zshrc"
alias zr="source ~/.zshrc"
#Pretty output
alias pretty="pygmentize -g -O encoding=utf-8"
##Reload MacOS DNS service after editing /etc/hosts
alias dnsreload="sudo killall -HUP mDNSResponder"
##Alias for tmuxinator
alias mux="tmuxinator"
##Sublime text
export SUBLIME=/usr/local/bin/subl
alias st="$SUBLIME $1"
alias stt="st ."
##Brew cask
alias casker="brew cask"
#Docker
alias drc='docker rm $(docker ps -aq)'
#Git
alias gst='git status'
alias gp='git pull '
